# Generated by Django 5.2.18 on 2026-10-09 03:06

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('porcao_padrao', models.CharField(max_length=50)),
                ('porcao_gramas', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('kcal', models.DecimalField(decimal_places=2, max_digits=7)),
                ('proteina_g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('carbo_g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gordura_g', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'alimento',
                'verbose_name_plural': 'catálogo de alimentos',
                'db_table': 'catalogo_alimentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='DiarioConsumo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_referencia', models.DateField()),
                ('total_agua_consumida_ml', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('status_dieta_cumprida', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'diário de consumo',
                'verbose_name_plural': 'diários de consumo',
                'db_table': 'diario_consumo',
                'ordering': ['usuario', '-data_referencia'],
            },
        ),
        migrations.CreateModel(
            name='Esporte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('met', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
            options={
                'verbose_name': 'esporte',
                'verbose_name_plural': 'esportes',
                'db_table': 'esportes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FichaTreino',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_ficha', models.CharField(max_length=100)),
                ('dia_semana', models.CharField(blank=True, choices=[('seg', 'Segunda-feira'), ('ter', 'Terça-feira'), ('qua', 'Quarta-feira'), ('qui', 'Quinta-feira'), ('sex', 'Sexta-feira'), ('sab', 'Sábado'), ('dom', 'Domingo')], max_length=3)),
            ],
            options={
                'verbose_name': 'ficha de treino',
                'verbose_name_plural': 'fichas de treino',
                'db_table': 'fichas_treino',
                'ordering': ['usuario', 'nome_ficha'],
            },
        ),
        migrations.CreateModel(
            name='RefeicaoPersonalizada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_refeicao', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'refeição personalizada',
                'verbose_name_plural': 'refeições personalizadas',
                'db_table': 'refeicoes_personalizadas',
                'ordering': ['usuario', 'nome_refeicao'],
            },
        ),
        migrations.CreateModel(
            name='ExercicioFicha',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_exercicio', models.CharField(max_length=100)),
                ('ordem_execucao', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('series_planejadas', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('repeticoes_planejadas', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='saude.fichatreino')),
            ],
            options={
                'verbose_name': 'exercício da ficha',
                'verbose_name_plural': 'exercícios da ficha',
                'db_table': 'exercicios_ficha',
                'ordering': ['ficha', 'ordem_execucao'],
            },
        ),
        migrations.CreateModel(
            name='MedidaCaseira',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('gramas', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medidas', to='saude.alimento')),
            ],
            options={
                'verbose_name': 'medida caseira',
                'verbose_name_plural': 'medidas caseiras',
                'db_table': 'medidas_caseiras',
                'ordering': ['alimento', 'gramas'],
            },
        ),
        migrations.CreateModel(
            name='RefeicaoPersonalizadaItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade_multiplicador', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saude.alimento')),
                ('refeicao_personalizada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='saude.refeicaopersonalizada')),
            ],
            options={
                'verbose_name': 'item da refeição',
                'verbose_name_plural': 'itens da refeição',
                'db_table': 'refeicoes_personalizadas_itens',
            },
        ),
        migrations.CreateModel(
            name='RegistroRefeicao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_refeicao', models.CharField(choices=[('cafe_manha', 'Café da manhã'), ('lanche_manha', 'Lanche da manhã'), ('almoco', 'Almoço'), ('lanche_tarde', 'Lanche da tarde'), ('jantar', 'Jantar'), ('ceia', 'Ceia')], max_length=15)),
                ('horario', models.DateTimeField()),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refeicoes', to='saude.diarioconsumo')),
                ('refeicao_personalizada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='saude.refeicaopersonalizada')),
            ],
            options={
                'verbose_name': 'refeição registrada',
                'verbose_name_plural': 'refeições registradas',
                'db_table': 'registros_refeicao',
                'ordering': ['-horario'],
            },
        ),
        migrations.CreateModel(
            name='RegistroRefeicaoItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saude.alimento')),
                ('medida_caseira', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='saude.medidacaseira')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='saude.registrorefeicao')),
            ],
            options={
                'verbose_name': 'alimento consumido',
                'verbose_name_plural': 'alimentos consumidos',
                'db_table': 'registros_refeicao_itens',
            },
        ),
        migrations.CreateModel(
            name='SessaoAtividade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inicio', models.DateTimeField()),
                ('duracao_minutos', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('intensidade', models.CharField(choices=[('leve', 'Leve'), ('moderada', 'Moderada'), ('intensa', 'Intensa'), ('maxima', 'Máxima')], max_length=10)),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('esporte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saude.esporte')),
                ('ficha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='saude.fichatreino')),
            ],
            options={
                'verbose_name': 'sessão de atividade',
                'verbose_name_plural': 'sessões de atividade',
                'db_table': 'sessoes_atividade',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='SerieExecutada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_serie', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('carga_kg', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('repeticoes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='saude.exercicioficha')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='saude.sessaoatividade')),
            ],
            options={
                'verbose_name': 'série executada',
                'verbose_name_plural': 'séries executadas',
                'db_table': 'series_executadas_historico',
                'ordering': ['-sessao__inicio', 'exercicio', 'numero_serie'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=150)),
                ('apelido', models.CharField(blank=True, max_length=20)),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Digite os 11 números do CPF, sem pontos.')])),
                ('celular', models.CharField(max_length=15)),
                ('aceitou_termos', models.BooleanField(default=False)),
                ('data_nascimento', models.DateField()),
                ('sexo_biologico', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], max_length=10)),
                ('altura_cm', models.IntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)])),
                ('peso_meta_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('biotipo', models.CharField(choices=[('ectomorfo', 'Ectomorfo'), ('mesomorfo', 'Mesomorfo'), ('endomorfo', 'Endomorfo')], max_length=10)),
                ('avatar_url', models.URLField(blank=True, max_length=2000)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('conta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
                'db_table': 'usuarios',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.AddField(
            model_name='sessaoatividade',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='saude.usuario'),
        ),
        migrations.CreateModel(
            name='RegistroXP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acao', models.CharField(choices=[('treino', 'Registrar partida / treino'), ('atividade_secundaria', 'Atividade secundária'), ('recorde_pessoal', 'Recorde pessoal'), ('checkin_refeicao', 'Check-in de refeição'), ('dieta_perfeita', 'Check-in de dieta perfeita'), ('meta_agua', 'Meta de água atingida'), ('combo_saude', 'Combo saúde (treino + dieta)')], max_length=25)),
                ('pontos', models.IntegerField()),
                ('data_referencia', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('refeicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='saude.registrorefeicao')),
                ('sessao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='saude.sessaoatividade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_xp', to='saude.usuario')),
            ],
            options={
                'verbose_name': 'registro de XP',
                'verbose_name_plural': 'histórico de XP',
                'db_table': 'historico_xp',
                'ordering': ['-data_referencia', '-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='refeicaopersonalizada',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saude.usuario'),
        ),
        migrations.CreateModel(
            name='PerfilGamificacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('streak_atual', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('pontos_experiencia', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('escudos_descanso', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('ultimo_dia_ativo', models.DateField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='saude.usuario')),
            ],
            options={
                'verbose_name': 'perfil de gamificação',
                'verbose_name_plural': 'perfis de gamificação',
                'db_table': 'perfil_gamificacao',
                'ordering': ['-pontos_experiencia'],
            },
        ),
        migrations.CreateModel(
            name='MetaNutricional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_inicio', models.DateField()),
                ('meta_agua_ml', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('meta_calorias', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('meta_proteina_g', models.DecimalField(decimal_places=1, max_digits=6)),
                ('meta_carbo_g', models.DecimalField(decimal_places=1, max_digits=6)),
                ('meta_gordura_g', models.DecimalField(decimal_places=1, max_digits=6)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saude.usuario')),
            ],
            options={
                'verbose_name': 'meta nutricional',
                'verbose_name_plural': 'metas nutricionais',
                'db_table': 'metas_nutricionais',
                'ordering': ['usuario', '-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoMedida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_registro', models.DateTimeField()),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('30')), django.core.validators.MaxValueValidator(Decimal('300'))])),
                ('objetivo_momento', models.CharField(choices=[('emagrecimento', 'Emagrecimento'), ('manutencao', 'Manutenção'), ('hipertrofia', 'Hipertrofia'), ('saude', 'Saúde e bem-estar')], max_length=15)),
                ('foto_shape_url', models.URLField(blank=True, max_length=2000)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saude.usuario')),
            ],
            options={
                'verbose_name': 'histórico de medida',
                'verbose_name_plural': 'histórico de medidas',
                'db_table': 'historico_medidas',
                'ordering': ['usuario', '-data_registro'],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60)),
                ('descricao', models.TextField(blank=True)),
                ('codigo_convite', models.CharField(max_length=12, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_criados', to='saude.usuario')),
            ],
            options={
                'verbose_name': 'grupo',
                'verbose_name_plural': 'grupos',
                'db_table': 'grupos',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='fichatreino',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saude.usuario'),
        ),
        migrations.AddField(
            model_name='diarioconsumo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saude.usuario'),
        ),
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
                ('descricao', models.TextField(blank=True)),
                ('metrica', models.CharField(choices=[('xp', 'Mais XP'), ('sessoes', 'Mais treinos/partidas'), ('dieta', 'Mais dias de dieta perfeita'), ('agua', 'Mais dias com meta de água')], max_length=15)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desafios', to='saude.grupo')),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desafios_criados', to='saude.usuario')),
            ],
            options={
                'verbose_name': 'desafio',
                'verbose_name_plural': 'desafios',
                'db_table': 'desafios',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Amizade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usuario_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amizades_enviadas', to='saude.usuario')),
                ('usuario_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amizades_recebidas', to='saude.usuario')),
            ],
            options={
                'verbose_name': 'amizade',
                'verbose_name_plural': 'amizades',
                'db_table': 'amizades',
            },
        ),
        migrations.CreateModel(
            name='ParticipanteDesafio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('desafio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='saude.desafio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desafios', to='saude.usuario')),
            ],
            options={
                'verbose_name': 'participante do desafio',
                'verbose_name_plural': 'participantes do desafio',
                'db_table': 'participantes_desafio',
                'constraints': [models.UniqueConstraint(fields=('desafio', 'usuario'), name='participante_unico_por_desafio')],
            },
        ),
        migrations.CreateModel(
            name='MembroGrupo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('papel', models.CharField(choices=[('admin', 'Administrador'), ('membro', 'Membro')], default='membro', max_length=10)),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='saude.grupo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='saude.usuario')),
            ],
            options={
                'verbose_name': 'membro do grupo',
                'verbose_name_plural': 'membros do grupo',
                'db_table': 'membros_grupo',
                'constraints': [models.UniqueConstraint(fields=('grupo', 'usuario'), name='membro_unico_por_grupo')],
            },
        ),
        migrations.CreateModel(
            name='EsporteUsuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequencia_semanal', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('intensidade', models.CharField(choices=[('leve', 'Leve'), ('moderada', 'Moderada'), ('intensa', 'Intensa'), ('maxima', 'Máxima')], max_length=10)),
                ('esporte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saude.esporte')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esportes', to='saude.usuario')),
            ],
            options={
                'verbose_name': 'esporte do usuário',
                'verbose_name_plural': 'esportes do usuário',
                'db_table': 'esportes_usuario',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'esporte'), name='esporte_unico_por_usuario')],
            },
        ),
        migrations.AddConstraint(
            model_name='diarioconsumo',
            constraint=models.UniqueConstraint(fields=('usuario', 'data_referencia'), name='diario_unico_por_dia'),
        ),
        migrations.AddConstraint(
            model_name='desafio',
            constraint=models.CheckConstraint(condition=models.Q(('data_fim__gte', models.F('data_inicio'))), name='desafio_fim_depois_do_inicio'),
        ),
        migrations.AddConstraint(
            model_name='amizade',
            constraint=models.UniqueConstraint(fields=('usuario_1', 'usuario_2'), name='amizade_unica'),
        ),
        migrations.AddConstraint(
            model_name='amizade',
            constraint=models.CheckConstraint(condition=models.Q(('usuario_1', models.F('usuario_2')), _negated=True), name='amizade_sem_si_mesmo'),
        ),
    ]
